#!/usr/bin/env python3
"""
Auto-generates docs/SCHEMA_REGISTRY.md from cyguide/schemas.
Acts as a linter: fails if any schema is missing documentation or pik_fields.
"""

import os
import sys
import importlib
import inspect
from pathlib import Path
from typing import Type

# Add the project root to sys.path
project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from cyguide.schemas.base import BaseFinding


def get_all_finding_schemas():
    schemas = []
    schemas_dir = project_root / "cyguide" / "schemas"
    
    for file in schemas_dir.glob("*.py"):
        if file.name == "__init__.py":
            continue
            
        module_name = f"cyguide.schemas.{file.stem}"
        module = importlib.import_module(module_name)
        
        for name, obj in inspect.getmembers(module):
            if (inspect.isclass(obj) and 
                issubclass(obj, BaseFinding) and 
                obj is not BaseFinding):
                schemas.append(obj)
    
    # Sort by schema_type if possible
    def get_schema_type(s):
        if hasattr(s, "model_fields") and "schema_type" in s.model_fields:
            return s.model_fields["schema_type"].default
        return getattr(s, "schema_type", "")

    return sorted(schemas, key=get_schema_type)


def generate_registry():
    schemas = get_all_finding_schemas()
    errors = []
    
    header = "| Schema Type | Description | PIK Fields | Parent | Associations |\n"
    header += "| :--- | :--- | :--- | :--- | :--- |\n"
    rows = []
    
    for schema in schemas:
        schema_type = "UNKNOWN"
        if hasattr(schema, "model_fields") and "schema_type" in schema.model_fields:
            schema_type = schema.model_fields["schema_type"].default
        elif hasattr(schema, "schema_type"):
            schema_type = schema.schema_type
            
        doc = schema.__doc__.strip() if schema.__doc__ else None
        pik_fields = getattr(schema, "pik_fields", [])
        
        # Linter checks
        if not doc:
            errors.append(f"ERROR: Schema '{schema.__name__}' is missing a docstring.")
        if not pik_fields:
            errors.append(f"ERROR: Schema '{schema.__name__}' is missing 'pik_fields' declaration.")
        if schema_type == "UNKNOWN" or schema_type is None:
            errors.append(f"ERROR: Schema '{schema.__name__}' is missing 'schema_type' declaration.")

        if errors:
            continue

        pik_str = ", ".join(f"`{f}`" for f in pik_fields)
        
        # Heuristic for parent
        parent = "—"
        if schema_type == "network.service":
            parent = "`network.host`"
        elif schema_type == "web.endpoint":
            parent = "`network.service`"
            
        # Heuristic/Detection for Associations
        assoc = "—"
        if schema_type == "dns.record":
            assoc = "`resolves_to` → `network.host`"
        elif schema_type == "domain.info":
            assoc = "`whois_data_for` → `dns.record`"
            
        rows.append(f"| `{schema_type}` | {doc} | {pik_str} | {parent} | {assoc} |")

    if errors:
        for err in errors:
            print(err, file=sys.stderr)
        sys.exit(1)

    content = "# Schema Registry\n\n"
    content += "This file is auto-generated by `scripts/generate_schema_registry.py`. **Do not edit manually.**\n\n"
    content += "This registry defines the shared language of CyGuide findings. Every tool must emit data conforming to one of these schemas.\n\n"
    content += header + "\n".join(rows) + "\n"

    output_path = project_root / "docs" / "SCHEMA_REGISTRY.md"
    with open(output_path, "w") as f:
        f.write(content)
    
    print(f"Successfully generated {output_path} with {len(rows)} schemas.")


if __name__ == "__main__":
    generate_registry()
